name: AAPS CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: 'nightscout/AndroidAPS'
          ref: '3.4.2.6'
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      

      - name: Build Debug APK
        run: ./gradlew assemblefullDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AAPS-Debug-3.4.2.6
          path: app/build/outputs/apk/**/*.apk
