name: AAPS CI

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Select AAPS Version'
        required: true
        default: '3.4.2.6'
        type: choice
        options:
          - 3.4.2.6
          - 3.4.2.4
          - 3.4.2.3
      buildVariant:
        description: 'Select Build Variant'
        required: true
        default: 'fullRelease'
        type: choice
        options:
          - fullRelease
          - fullDebug

jobs:
  build:
    name: Build AAPS
    runs-on: ubuntu-latest
    steps:
      - name: Decode Secrets Keystore Set and Oauth
        run: |
          if [ -n "${{ secrets.KEYSTORE_SET }}" ]; then
            echo "🔮 Decoding KEYSTORE_SET..."
            echo "${{ secrets.KEYSTORE_SET }}" | base64 -d --ignore-garbage > keystore_clean.txt
          fi

      - name: Checkout source code at tag
        uses: actions/checkout@v4
        with:
          repository: 'nightscout/AndroidAPS'
          ref: ${{ github.event.inputs.tagName }}
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decode keystore file
        run: |
          mkdir -p $RUNNER_TEMP/keystore
          echo "${{ secrets.KEYSTORE_SET }}" | base64 -d --ignore-garbage > $RUNNER_TEMP/keystore/keystore.jks

      - name: Build with Gradle
        run: |
          git clone --branch ${{ github.event.inputs.tagName }} https://github.com .
          ./gradlew assemble${{ github.event.inputs.buildVariant }}
        env:
          KEYSTORE_FILE: ${{ runner.temp }}/keystore/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AAPS-${{ github.event.inputs.tagName }}-${{ github.event.inputs.buildVariant }}
          path: app/build/outputs/apk/**/*.apk
